/**
 * Calling user function kni.test.Bridge.mixed
 * @param number kotlin.Long -> com.dshatz.kni.binding.jlong (via Simple)
 * @param value kotlin.CharArray -> com.dshatz.kni.binding.jcharArray (via Convertable)
 * @param upper kotlin.Boolean -> com.dshatz.kni.binding.jboolean (via Convertable)
 * @param char kotlin.Char -> com.dshatz.kni.binding.jchar (via Convertable)
 *
 * @return kotlin.String <- com.dshatz.kni.binding.jstring
 */
@CName("Java_kni_test_Bridge_mixedExternal")
@OptIn(ExperimentalForeignApi::class, ExperimentalNativeApi::class)
public fun _mixedJNI(
    env: CPointer<JNIEnvVar>,
    clazz: jobject,
    number: jlong,
    `value`: jcharArray,
    upper: jboolean,
    char: jchar,
): jstring {
    // generated by Kotlin-JNI
    // this calls the actual fun you defined above in the native sourceset.
    val env = env.GetAndAttach()!!
    return (kni.test.Bridge.mixed(
        number,
        (`value`).toKCharArray(env)!!,
        (upper).toKBoolean(env)!!,
        (char).toKChar(env)!!
    )).toJString(env)!!
}