package com.dshatz.kni.callable

import com.dshatz.kni.CNameUtils
import com.dshatz.kni.Registry
import com.dshatz.kni.TypeInfo
import com.dshatz.kni.TypeMapper
import com.dshatz.kni.TypeMatcher
import com.dshatz.kni.annotations.Callable
import com.google.devtools.ksp.closestClassDeclaration
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.symbol.KSFunctionDeclaration
import com.google.devtools.ksp.symbol.Modifier
import com.squareup.kotlinpoet.AnnotationSpec
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.MemberName
import com.squareup.kotlinpoet.ParameterSpec
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.asTypeName
import com.squareup.kotlinpoet.ksp.toClassName
import com.squareup.kotlinpoet.ksp.toTypeName

class CallableProcessor(
    private val registry: Registry,
    private val logger: KSPLogger
) {
    private val mapper: TypeMapper = TypeMapper(registry)

    fun generateNativeProxies(
        funs: List<KSFunctionDeclaration>,
    ): List<FileSpec> {
        return funs.groupBy { it.parentDeclaration }.map { (parent, functions) ->
            val cls = parent?.closestClassDeclaration()!!.toClassName()

            val funSpecs = functions.map { f ->
                if (
                    f.modifiers.contains(Modifier.ACTUAL) &&
                    f.annotations.any { it.annotationType.toTypeName() == Callable::class.asTypeName() }) {
                    logger.warn("@Callable can only be applied to a top-level expect function.", f)
                }
                val params = f.parameters.map {
                    ParamInfo(it.name!!.asString(), mapper.mapType(it.type))
                }

                val returnType = mapper.mapType(f.returnType!!)

                val actualMember = MemberName(cls, f.simpleName.asString())
                generateCnameFunction(actualMember, params, returnType)
            }

            FileSpec.builder(cls)
                .addFunctions(funSpecs)
                .build()
        }
    }

    private fun generateCnameFunction(
        callFun: MemberName,
        params: List<ParamInfo>,
        returnType: TypeInfo
    ): FunSpec {

        val jniCName = CNameUtils.jniFunctionCName(
            packageName = callFun.packageName,
            className = callFun.enclosingClassName!!.simpleName,
            functionName = callFun.simpleName + "External"
        )

        val paramCodes = params.map {
            it.typeInfo.unpackCode(CodeBlock.of("%N", it.name))
        }
        val paramConversionCode = paramCodes.joinToString()
        val callUserCode = CodeBlock.of("%M(%L)", callFun, paramConversionCode)
        val packResult = returnType.packCode(callUserCode)

        val funName = "_${callFun.simpleName}JNI"
        val f = FunSpec.builder(funName)
            .returns(
                returnType.jniType.nativeType,
                kdoc = CodeBlock.of("${returnType.kotlinType} <- ${returnType.jniType.nativeType}")
            )
            .addKdoc("Calling user function $callFun")
            .addAnnotation(AnnotationSpec.builder(CNameUtils.CName).addMember(CodeBlock.of("%S", jniCName)).build())
            .addAnnotation(CNameUtils.NativeOptIn)
            .addParameter("env", TypeMatcher.Environment)
            .addParameter("clazz", TypeMatcher.JObject)
            .addParameters(params.map {
                ParameterSpec
                    .builder(it.name, it.typeInfo.jniType.nativeType)
                    .addKdoc("${it.typeInfo.kotlinType} -> ${it.typeInfo.jniType.nativeType} (via ${it.typeInfo::class.simpleName})")
                    .build()
            })
            .addCode(
                CodeBlock.builder()
                    .addStatement("// generated by Kotlin-JNI")
                    .addStatement("val env = env.%M()!!", TypeMatcher.Method.GetAndAttach)
                    .addStatement("return %L", packResult)
                    .build()
            )
            .build()
        return f
        /*return FileSpec.builder(ClassName(callFun.packageName, funName))
            .addFunction(f)
            .build()*/
    }

    fun generateJvmActuals(
        funs: List<KSFunctionDeclaration>,
    ): List<FileSpec> {
        return funs.groupBy { it.parentDeclaration }.map { (parent, functions) ->
            val cls = parent?.closestClassDeclaration()!!.toClassName()
            val funNames = functions.associateWith { f ->
                MemberName(cls, f.simpleName.asString())
            }

            val funSpecs = functions.flatMap { f ->

                val externalMember = funNames[f]!!.let {
                    MemberName(f.packageName.asString(), f.simpleName.asString() + "External")
                }
                val params = f.parameters.map {
                    it.name!!.asString() to mapper.mapType(it.type)
                }
                val returnType = mapper.mapType(f.returnType!!)

                val funSpec = FunSpec.builder(funNames[f]!!)
                    .addModifiers(KModifier.ACTUAL)
                    .returns(returnType.kotlinType)
                    .apply {
                        params.forEach { (name, typeInfo) ->
                            addParameter(ParameterSpec.builder(
                                name = name,
                                type = typeInfo.kotlinType
                            ).build())
                        }
                    }
                    .apply {
                        val paramPacking = params.map { (name, typeInfo) ->
                            typeInfo.packCodeJvm(CodeBlock.of("%N", name))
                        }
                        val paramsCode = paramPacking.joinToString()
                        val callExternalCode = CodeBlock.of("%M(%L)", externalMember, paramsCode)
                        addCode(
                            CodeBlock.builder()
                                .addStatement("return %L", returnType.unpackCodeJvm(callExternalCode))
                                .build()
                        )
                    }.build()


                val externalSpec = FunSpec.builder(externalMember)
                    .addModifiers(KModifier.EXTERNAL)
                    .returns(returnType.jniType.jvmType)
                    .apply {
                        params.forEach { (name, typeInfo) ->
                            addParameter(ParameterSpec.builder(
                                name = name,
                                type = typeInfo.jniType.jvmType,
                            ).build())
                        }
                    }.build()
                listOf(funSpec, externalSpec)
            }

            val classSpec = TypeSpec.objectBuilder(cls)
                .addModifiers(KModifier.ACTUAL)
                .addFunctions(funSpecs)
                .build()

            FileSpec.builder(cls)
                .addType(classSpec)
                .build()
        }
    }

    fun List<CodeBlock>.joinToString(): CodeBlock {
        return CodeBlock.of(
            generateSequence { "%L" }.take(size).joinToString(", "),
            args = this.toTypedArray()
        )
    }

    data class ParamInfo(
        val name: String,
        val typeInfo: TypeInfo,
    )
}