package com.dshatz.kni.callable

import com.dshatz.kni.*
import com.dshatz.kni.kspfix.FunLocation
import com.dshatz.kni.kspfix.functionLocation
import com.dshatz.kni.kspfix.withLocations
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.symbol.KSFunctionDeclaration
import com.squareup.kotlinpoet.*

class CallableProcessor(
    private val registry: Registry,
    private val logger: KSPLogger
) {
    private val mapper: TypeMapper = TypeMapper(registry)

    fun generateNativeFuns(
        funs: List<KSFunctionDeclaration>,
    ): List<FileSpec> {
        return funs.withLocations().groupBy { it.location.className }.map { (parent, functions) ->

            val funSpecs = functions.map { (f, location) ->
                val params = f.parameters.map {
                    ParamInfo(it.name!!.asString(), mapper.mapType(it.type))
                }

                val returnType = mapper.mapType(f.returnType!!)

                generateCnameFunction(location.toMemberName(f.simpleName.asString()), location, params, returnType)
            }

            logger.warn("Adding file ${parent.simpleName}: generateNativeFuns(${funs.joinToString { it.simpleName.asString() }})")
            FileSpec.builder(parent)
                .addFunctions(funSpecs)
                .build()
        }
    }

    private fun generateCnameFunction(
        callFun: MemberName,
        funLocation: FunLocation,
        params: List<ParamInfo>,
        returnType: TypeInfo
    ): FunSpec {

        val jniCName = CNameUtils.jniFunctionCName(
            packageName = callFun.packageName,
            className = funLocation.classNameKt.simpleName,
            functionName = callFun.simpleName + "External"
        )

        val paramCodes = params.map {
            it.typeInfo.unpackCode(CodeBlock.of("%N", it.name))
        }
        val paramConversionCode = paramCodes.joinToString()
        val callUserCode = CodeBlock.of("%M(%L)", callFun, paramConversionCode)
        val packResult = returnType.packCode(callUserCode)

        val funName = "_${callFun.simpleName}JNI"
        val f = FunSpec.builder(funName)
            .returns(
                returnType.jniType.nativeType,
                kdoc = CodeBlock.of("${returnType.kotlinType} <- ${returnType.jniType.nativeType}")
            )
            .addKdoc("Calling user function $callFun")
            .addAnnotation(AnnotationSpec.builder(CNameUtils.CName).addMember(CodeBlock.of("%S", jniCName)).build())
            .addAnnotation(CNameUtils.NativeOptIn)
            .addParameter("env", TypeMatcher.Environment)
            .addParameter("clazz", TypeMatcher.JObject)
            .addParameters(params.map {
                ParameterSpec
                    .builder(it.name, it.typeInfo.jniType.nativeType)
                    .addKdoc("${it.typeInfo.kotlinType} -> ${it.typeInfo.jniType.nativeType} (via ${it.typeInfo::class.simpleName})")
                    .build()
            })
            .addCode(
                CodeBlock.builder()
                    .addStatement("// generated by Kotlin-JNI")
                    .addStatement("val env = env.%M()!!", TypeMatcher.Method.GetAndAttach)
                    .addStatement("return %L", packResult)
                    .build()
            )
            .build()
        return f
    }

    fun generateJvmActuals(
        funs: List<KSFunctionDeclaration>,
    ): List<FileSpec> {
        return funs.withLocations().groupBy { it.location.className }.map { (parent, functions) ->
            val funNames = functions.associate { f ->
                f.f to MemberName(f.location.className, f.f.simpleName.asString())
            }

            val funSpecs = functions.groupBy { it.location.topLevel }.mapValues { (_, functions) ->
                functions.flatMap { (f, loc) ->

                    val externalMember = funNames[f]!!.let {
                        MemberName(f.packageName.asString(), f.simpleName.asString() + "External")
                    }
                    val params = f.parameters.map {
                        it.name!!.asString() to mapper.mapType(it.type)
                    }
                    val returnType = mapper.mapType(f.returnType!!)

                    val funSpec = FunSpec.builder(funNames[f]!!)
                        .addModifiers(KModifier.ACTUAL)
                        .returns(returnType.kotlinType)
                        .apply {
                            params.forEach { (name, typeInfo) ->
                                addParameter(ParameterSpec.builder(
                                    name = name,
                                    type = typeInfo.kotlinType
                                ).build())
                            }
                        }
                        .apply {
                            val paramPacking = params.map { (name, typeInfo) ->
                                typeInfo.packCodeJvm(CodeBlock.of("%N", name))
                            }
                            val paramsCode = paramPacking.joinToString()
                            val callExternalCode = CodeBlock.of("%M(%L)", externalMember, paramsCode)
                            addCode(
                                CodeBlock.builder()
                                    .addStatement("return %L", returnType.unpackCodeJvm(callExternalCode))
                                    .build()
                            )
                        }.build()


                    val externalSpec = FunSpec.builder(externalMember)
                        .addModifiers(KModifier.EXTERNAL)
                        .returns(returnType.jniType.jvmType)
                        .apply {
                            params.forEach { (name, typeInfo) ->
                                addParameter(ParameterSpec.builder(
                                    name = name,
                                    type = typeInfo.jniType.jvmType,
                                ).build())
                            }
                        }.build()
                    listOf(funSpec, externalSpec)
                }
            }

            val topLevel = funSpecs.get(true) ?: emptyList()
            val classLevel = funSpecs.get(false) ?: emptyList()
            FileSpec.builder(parent)
                .addFunctions(topLevel)
                .apply {
                    if (classLevel.isNotEmpty()) {
                        addType(TypeSpec.objectBuilder(parent)
                            .addModifiers(KModifier.ACTUAL)
                            .addFunctions(classLevel)
                            .build()
                        )
                    }
                }
                .build()

        }
    }

    fun List<CodeBlock>.joinToString(): CodeBlock {
        return CodeBlock.of(
            generateSequence { "%L" }.take(size).joinToString(", "),
            args = this.toTypedArray()
        )
    }

    data class ParamInfo(
        val name: String,
        val typeInfo: TypeInfo,
    )
}