name: Test

on:
  pull_request_target:
    branches:
      - master
    paths-ignore:
      - 'doc/**'
      - '**.md'
      - '**.txt'
  push:
    branches:
      - master
    paths-ignore:
      - 'doc/**'
      - '**.md'
      - '**.txt'

jobs:
  test-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup
        uses: ./.github/actions/build-setup
        with:
          configuration_cache_key: secrets.GRADLE_CONFIGURATION_CACHE_KEY

      - name: Build and Test
        run: ./gradlew allTests e2e:assembleAndroidDeviceTest
        env:
          GRADLE_OPTS: >-
            -Dorg.gradle.jvmargs="-Xmg12g -XX:+UseG1GC -XX:MaxMetaspaceSize=512m"
            -Dkotlin.daemon.jvm.options="-Xmx2048m"
      - name: Upload Test Report
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: test-report-ubuntu-latest
          path: ./**/build/test-results/**/*.xml
          archive: false
          retention-days: 5
      - name: Upload Android Test APK
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: e2e-androidTest.apk
          path: ./e2e/build/outputs/apk/androidTest/e2e-androidTest.apk
          archive: false

  test-windows:
    permissions:
      contents: read
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup
        uses: ./.github/actions/build-setup
        with:
          configuration_cache_key: secrets.GRADLE_CONFIGURATION_CACHE_KEY
      - name: Build and Test
        run: ./gradlew allTests
        env:
          GRADLE_OPTS: >-
            -Dorg.gradle.jvmargs="-Xmg12g -XX:+UseG1GC -XX:MaxMetaspaceSize=512m"
            -Dkotlin.daemon.jvm.options="-Xmx2048m"
      - name: Upload Test Report
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: test-report-windows-latest
          path: ./**/build/test-results/**/*.xml
          archive: false

  test-macos:
    permissions:
      contents: read
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup
        uses: ./.github/actions/build-setup
        with:
          configuration_cache_key: secrets.GRADLE_CONFIGURATION_CACHE_KEY
      - name: Build and Test
        run: ./gradlew allTests
        env:
          GRADLE_OPTS: >-
            -Dorg.gradle.jvmargs="-Xmg5g -XX:+UseG1GC -XX:MaxMetaspaceSize=512m"
            -Dkotlin.daemon.jvm.options="-Xmx2048m"
      - name: Upload Test Report
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: test-report-macos-latest
          path: ./**/build/test-results/**/*.xml
          archive: false

  test-android:
    needs: ["test-linux"]
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v8
        with:
          name: e2e-androidTest.apk
      - name: Set up google cloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCLOUD_AUTH }}

      - name: Auth google cloud
        uses: 'google-github-actions/auth@v3'
        with:
          project_id: 'kotlin-jni'
          credentials_json: ${{ secrets.GCLOUD_AUTH }}

      - name: Set current project
        run: gcloud config set project ${{ secrets.FIREBASE_PROJECT_ID }}

      - name: Run Instrumentation Tests in Firebase Test Lab
        continue-on-error: true
        env:
          APP_DEBUG_LOCATION: e2e-androidTest.apk
          ANDROID_TEST_LOCATION: e2e-androidTest.apk
          DEVICE_MODEL: SmallPhone.arm,version=35
        run: >
          gcloud firebase test android run
          --type instrumentation
          --app $APP_DEBUG_LOCATION
          --test $ANDROID_TEST_LOCATION
          --device model=$DEVICE_MODEL
          --results-bucket=jni-firebase-test
          --results-dir="run-${{ github.run_id }}"
          --no-record-video
      - name: Download Results
        run: |
          mkdir -p firebase-results
          # Replace 'your-bucket-name' with your actual bucket (e.g. test-lab-xxxx)
          gcloud storage cp -r "gs://jni-firebase-test/run-${{ github.run_id }}/**/test_result_*.xml" ./firebase-results/

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: test-report-android
          path: firebase-results/

  publish-results:
    needs:
      - test-linux
      - test-android
      - test-macos
      - test-windows
    runs-on: ubuntu-latest
    if: always()
    permissions:
      contents: read
      checks: write
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v8
        with:
          path: artifacts

      - name: Detailed Test Report Linux
        uses: dorny/test-reporter@v1
        continue-on-error: true
        if: always()
        with:
          name: "Linux"
          path: "artifacts/test-report-Linux/**/*.xml"
          reporter: java-junit

      - name: Detailed Test Report Windows
        uses: dorny/test-reporter@v1
        continue-on-error: true
        if: always()
        with:
          name: "Windows"
          path: "artifacts/test-report-Windows/**/*.xml"
          reporter: java-junit

      - name: Detailed Test Report MacOS
        uses: dorny/test-reporter@v1
        continue-on-error: true
        if: always()
        with:
          name: "MacOS"
          path: "artifacts/test-report-macOS/**/*.xml"
          reporter: java-junit

      - name: Detailed Test Report Android
        uses: dorny/test-reporter@v1
        if: always()
        continue-on-error: true
        with:
          name: "Android"
          path: "artifacts/test-report-android/**/*.xml"
          reporter: java-junit
